### ISSUE TITLE
alphabetic ordering does not tell support status

### ISSUE THREAD

**Issue by fricklerhandwerk** [nix-community/awesome-nix#123]
where support means both
- state of maturity and maintenance
- community recommendation as best practice

this is especially problematic where there are multiple contenders for a use case.

related: https://github.com/NixOS/nixos-foundation/issues/39 (decide what is a project in the Nix ecosystem)

**Comment by houstdav000** [comment]
The support/maturity level of the project is kinda beyond the scope of an "awesome list". There is _some_ level of that I recently introduced by creating a separate `DEPRECATED.md` file with projects that have been archived or otherwise unmaintained, specific levels of project support and maturity, whether WIP, fully functional and supported, or undersupported is beyond the scope of an "awesome list".

Information like maturity and maintenance though might be better put in a more exhaustive list, while _community_ recommendations might actually be an even shorter list. That might be better put on a Wiki or something.

The purpose of an "awesome list" is to provide projects that we recommend. To only recommend a single contender for every use case would be like asserting there's only one "best practice" way to implement something (ex: What's the "best practice" editor? Should we only have VSCode Nix projects listed? Vim? Emacs?).

I'd probably agree that the list has become too large, with some of these resources listed underutilized, and so might not hit the bar of "awesome" (which is extremely subjective). That being said, I'm hesitant to remove items from the list. I only use a small subset of these tools, and personally don't like some of the things on here (ex: Alejandra), but that's not to say they're not _community_ recommended.

> Research if the stuff you're including is actually awesome. Only put stuff on the list that you or another contributor can personally recommend. You should rather leave stuff out than include too much.

- [The Awesome Manifesto](https://github.com/sindresorhus/awesome/blob/main/awesome.md)

**Comment by fricklerhandwerk** [comment]
To clarify, I'm not suggesting removing competing offers, but making them more distinguishable from each other. Maybe making the comments more descriptive would already help enough.

**Comment by cyntheticfox** [comment]
Closing, since #128 I believe resolved this, and #156 may help
