### ISSUE TITLE
summaries should should be factual

### ISSUE THREAD

**Issue by fricklerhandwerk** [nix-community/awesome-nix#125]
many summaries currently contain either value judgement ("simple", "awesome", "quickly", "better") or nondescript statements ("Beat your package expressions into a shape").

that does not help readers figure out how and why a recommendation may be useful to them.

summaries should consistently and factually state for every resource
- what it is for
- why it is part of this collection
- (optional) how it differs from competing offers, trade-offs, etc.

related: https://github.com/nix-community/awesome-nix/issues/123

**Comment by houstdav000** [comment]
Given [the official comment guidelines](https://github.com/sindresorhus/awesome/blob/main/awesome.md#comment-on-why-something-is-awesome>), I'm inclined to agree.

Might even be good to phrase them in a manner like agile "user stories":

`A [tool that does thing with special attribute] so that [benefit to user].`
