### ISSUE TITLE
Add history.nix-packages.com

### ISSUE THREAD

**Issue by RikudouSage** [nix-community/awesome-nix#203]
This is a project of mine that aims to replace https://lazamar.co.uk/nix-versions/ because that one does not seem updated.

It's available at https://history.nix-packages.com

**Comment by SuperSandro2000** [comment]
I am missing some good advice on that website like
- that old packages are insecure and you are downloading all of the old and insecure dependencies
- that things might not work at all and require also older versions of nix itself or your kernel

To demonstrate that I just grabbed the oldest version of firefox and it immediately broke:

```
 ▶ command nix-shell -p firefox -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/c9982118fc1be9bbe87f3ed00cd248e4c4c4dfc6.tar.gz
error: undefined variable 'pkgs'

       at «string»:1:42:

            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (firefox) ]; } ""
             |                                          ^
```

Also installing old versions via nix-env isn't a good advice because nix-env is really great in being forgotten and doing the wrong thing and leaving people with old packages without them actively seeing it anymore.

**Comment by cyntheticfox** [comment]
Also, I appreciate the work, but it's too new at the moment. I also do agree with Sandro's points

**Comment by RikudouSage** [comment]
As you wish.
