### ISSUE TITLE
List of nix-config, nixos-config repos?

### ISSUE THREAD

**Issue by colemickens** [nix-community/awesome-nix#33]
Hi!

I have been using NixOS for a long time and feel relatively "plugged in", yet I'm constantly finding things in other Nix users's configuration repos.

Is there interest in maintaining a list of those repos here?

Bonus, we could call out flakes-enabled repos which are somewhat hard to find now and useful for folks looking to test out flakes.

**Comment by zimbatm** [comment]
Sounds good! If the list becomes too large it could be moved to a separate page.

Here is a good start: https://github.com/nix-community/NUR/blob/master/repos.json

**Comment by Mic92** [comment]
Sound good to me.

**Comment by abathur** [comment]
I think this could be useful as well, though I want to think-out-loud about currency, best-practice, and metadata, because I think these will add the most value if they are well-curated?

In my experience, there are some tricky things about referencing user config repos (exacerbated for newbies):
- Config is predicated on using some other ecosystem project that you aren't familiar with. One way this manifests is example is finding a module/program config that would be useful but not realizing it's implemented elsewhere.
- Config uses older patterns for things. If the config is out of date they may not work at all, or maybe they work fine but aren't best-practice anymore. 
- Highly-modular configs that look really nice and appear to just automagically work, when in fact there's some importing going on to make it work that is hard to find.
- Some such repos are quite large/modular, and it can be hard to find the interesting parts without some knowledge of the organizational patterns used (and there isn't enough of a consensus pattern to just learn this once...)
- Directly finding examples of good patterns is very hard. I mostly just explore everything I find while I'm looking for examples of someone configuring a service I need to use, and get sidetracked exploring the patterns they use.

All-around, I think this has the most promise if:
- It can avoid turning into a dumping ground for every nix/nixos config repo just because it exists (but it's OK to have a section for that purpose...).
- Each entry (whether by category, description, metadata, or all of these) has a very specific/clear reason it's included (it's here to demonstrate this organizational pattern, or because it shows how you can have a different config per hostname, or concurrently pull from unstable and a release channel, etc.) with enough context/sublinks for people who don't know their way around yet to readily find those parts.
- There's some way to contextualize things that shouldn't be indiscriminately adopted, like:
   - Yes, this works, but it's the old way of doing things and it has known deficiencies, so you should do this instead.
   - It provides the best example of X, but don't pick up how it does Y (because it's deprecated/idiomatic).
   - It does X, and many people ask for X, but you should think long-and-hard because it has all of these consequences.
   - It's a great example of how to use flakes, but here's how to decide if you're ready to dive in, yet.

**Comment by zimbatm** [comment]
Thanks for reminding us that the list is supposed to be curated for quality @abathur. Things are going to happen in corners that are not evenly distributed.

Maybe it would help to fix https://nix-community.github.io/nur-search/ and then list that in awesome-nix directly instead?

**Comment by Mic92** [comment]
> Thanks for reminding us that the list is supposed to be curated for quality @abathur. Things are going to happen in corners that are not evenly distributed.
> 
> Maybe it would help to fix [nix-community.github.io/nur-search](https://nix-community.github.io/nur-search/) and then list that in awesome-nix directly instead?

@zimbatm what is broken in nur-search?

**Comment by zimbatm** [comment]
me apparently, it's working great! I was confused by the UI for a bit and didn't see the content on the left.

**Comment by zimbatm** [comment]
So I was thinking, how about making NUR more visible on https://nur.nix-community.org/ or even a new domain? Then that would encourage users to participate even more in that experiment.

**Comment by Mic92** [comment]
> So I was thinking, how about making NUR more visible on [nur.nix-community.org](https://nur.nix-community.org/) or even a new domain? Then that would encourage users to participate even more in that experiment.

I am fine with that.
